name: Check against Python msgpack

on: push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make check
      run: make check

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cffi msgpack
    - name: Build extension
      run: python build_check.py
    - name: Check
      run: python check.py
