name: Test

on: push

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make check
      run: make check
